name: projeto terraform kubenet aws docker github action

on:
  push:
    branches:
      - main  

jobs:
  projeto:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout do codigo
        uses: actions/checkout@v4

      
      - name: Mensagem de funcionamento
        run: echo "Iniciando o build das imagens Docker do RPG..."

      
     
      - name: Rodando Docker - Backend
        run: docker build -t meu-rpg-backend -f ./web/backend/Dockerfile ./web/backend

     
      - name: Rodando Docker - Frontend
        run: docker build -t meu-rpg-frontend -f ./web/Frontend/Dockerfile ./web/Frontend
      

