version: '3.8'

services:
  
  backend:
    build:
      context: ./web/Backend
      dockerfile: dockerfile
    container_name: rpg-backend
    ports:
      - "3000:3000" 
    networks:
      - rpg-network

  
  frontend:
    build:
      context: ./web
      dockerfile: dockerfile 
    container_name: rpg-frontend
    ports:
      - "80:80" 
    depends_on:
      - backend 


networks:
  rpg-network:
    driver: bridge